# bundle exec jekyll serve --port 4001
title: mini-book
description: This is a little programming notebook. Essentially, I just dump whatever I find interesting.
theme: just-the-docs

url: https://darrela.github.io/mini-book

color_scheme: dark

callouts_level: loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

nav_sort: case_sensitive # Capital letters sorted before lowercase

back_to_top: true
back_to_top_text: 'Back to top'
